<option value="">@changeLang('Select Country')</option>
<option value="Afghanistan">@changeLang('Afghanistan')</option>
<option value="Åland Islands">@changeLang('Åland Islands')</option>
<option value="Albania">@changeLang('Albania')</option>
<option value="Algeria">@changeLang('Algeria')</option>
<option value="American Samoa">@changeLang('American Samoa')</option>
<option value="Andorra">@changeLang('Andorra')</option>
<option value="Angola">@changeLang('Angola')</option>
<option value="Anguilla">@changeLang('Anguilla')</option>
<option value="Antarctica">@changeLang('Antarctica')</option>
<option value="Antigua and Barbuda">@changeLang('Antigua and Barbuda')</option>
<option value="Argentina">@changeLang('Argentina')</option>
<option value="Armenia">@changeLang('Armenia')</option>
<option value="Aruba">@changeLang('Aruba')</option>
<option value="Australia">@changeLang('Australia')</option>
<option value="Austria">@changeLang('Austria')</option>
<option value="Azerbaijan">@changeLang('Azerbaijan')</option>
<option value="Bahamas">@changeLang('Bahamas')</option>
<option value="Bahrain">@changeLang('Bahrain')</option>
<option value="Bangladesh">@changeLang('Bangladesh')</option>
<option value="Barbados">@changeLang('Barbados')</option>
<option value="Belarus">@changeLang('Belarus')</option>
<option value="Belgium">@changeLang('Belgium')</option>
<option value="Belize">@changeLang('Belize')</option>
<option value="Benin">@changeLang('Benin')</option>
<option value="Bermuda">@changeLang('Bermuda')</option>
<option value="Bhutan">@changeLang('Bhutan')</option>
<option value="Bolivia">@changeLang('Bolivia')</option>
<option value="Bosnia and Herzegovina">@changeLang('Bosnia and Herzegovina')</option>
<option value="Botswana">@changeLang('Botswana')</option>
<option value="Bouvet Island">@changeLang('Bouvet Island')</option>
<option value="Brazil">@changeLang('Brazil')</option>
<option value="British Indian Ocean Territory">@changeLang('British Indian Ocean Territory')</option>
<option value="Brunei Darussalam">@changeLang('Brunei Darussalam')</option>
<option value="Bulgaria">@changeLang('Bulgaria')</option>
<option value="Burkina Faso">@changeLang('Burkina Faso')</option>
<option value="Burundi">@changeLang('Burundi')</option>
<option value="Cambodia">@changeLang('Cambodia')</option>
<option value="Cameroon">@changeLang('Cameroon')</option>
<option value="Canada">@changeLang('Canada')</option>
<option value="Cape Verde">@changeLang('Cape Verde')</option>
<option value="Cayman Islands">@changeLang('Cayman Islands')</option>
<option value="Central African Republic">@changeLang('Central African Republic')</option>
<option value="Chad">@changeLang('Chad')</option>
<option value="Chile">@changeLang('Chile')</option>
<option value="China">@changeLang('China')</option>
<option value="Christmas Island">@changeLang('Christmas Island')</option>
<option value="Cocos (Keeling) Islands">@changeLang('Cocos (Keeling) Islands')</option>
<option value="Colombia">@changeLang('Colombia')</option>
<option value="Comoros">@changeLang('Comoros')</option>
<option value="Congo">@changeLang('Congo')</option>
<option value="Congo, The Democratic Republic of The">@changeLang('Congo, The Democratic Republic of The')</option>
<option value="Cook Islands">@changeLang('Cook Islands')</option>
<option value="Costa Rica">@changeLang('Costa Rica')</option>
<option value="Cote D'ivoire">@changeLang('Cote D\'ivoire')</option>
<option value="Croatia">@changeLang('Croatia')</option>
<option value="Cuba">@changeLang('Cuba')</option>
<option value="Cyprus">@changeLang('Cyprus')</option>
<option value="Czech Republic">@changeLang('Czech Republic')</option>
<option value="Denmark">@changeLang('Denmark')</option>
<option value="Djibouti">@changeLang('Djibouti')</option>
<option value="Dominica">@changeLang('Dominica')</option>
<option value="Dominican Republic">@changeLang('Dominican Republic')</option>
<option value="Ecuador">@changeLang('Ecuador')</option>
<option value="Egypt">@changeLang('Egypt')</option>
<option value="El Salvador">@changeLang('El Salvador')</option>
<option value="Equatorial Guinea">@changeLang('Equatorial Guinea')</option>
<option value="Eritrea">@changeLang('Eritrea')</option>
<option value="Estonia">@changeLang('Estonia')</option>
<option value="Ethiopia">@changeLang('Ethiopia')</option>
<option value="Falkland Islands (Malvinas)">@changeLang('Falkland Islands (Malvinas)')</option>
<option value="Faroe Islands">@changeLang('Faroe Islands')</option>
<option value="Fiji">@changeLang('Fiji')</option>
<option value="Finland">@changeLang('Finland')</option>
<option value="France">@changeLang('France')</option>
<option value="French Guiana">@changeLang('French Guiana')</option>
<option value="French Polynesia">@changeLang('French Polynesia')</option>
<option value="French Southern Territories">@changeLang('French Southern Territories')</option>
<option value="Gabon">@changeLang('Gabon')</option>
<option value="Gambia">@changeLang('Gambia')</option>
<option value="Georgia">@changeLang('Georgia')</option>
<option value="Germany">@changeLang('Germany')</option>
<option value="Ghana">@changeLang('Ghana')</option>
<option value="Gibraltar">@changeLang('Gibraltar')</option>
<option value="Greece">@changeLang('Greece')</option>
<option value="Greenland">@changeLang('Greenland')</option>
<option value="Grenada">@changeLang('Grenada')</option>
<option value="Guadeloupe">@changeLang('Guadeloupe')</option>
<option value="Guam">@changeLang('Guam')</option>
<option value="Guatemala">@changeLang('Guatemala')</option>
<option value="Guernsey">@changeLang('Guernsey')</option>
<option value="Guinea">@changeLang('Guinea')</option>
<option value="Guinea-bissau">@changeLang('Guinea-bissau')</option>
<option value="Guyana">@changeLang('Guyana')</option>
<option value="Haiti">@changeLang('Haiti')</option>
<option value="Heard Island and Mcdonald Islands">@changeLang('Heard Island and Mcdonald Islands')</option>
<option value="Holy See (Vatican City State)">@changeLang('Holy See (Vatican City State)')</option>
<option value="Honduras">@changeLang('Honduras')</option>
<option value="Hong Kong">@changeLang('Hong Kong')</option>
<option value="Hungary">@changeLang('Hungary')</option>
<option value="Iceland">@changeLang('Iceland')</option>
<option value="India">@changeLang('India')</option>
<option value="Indonesia">@changeLang('Indonesia')</option>
<option value="Iran, Islamic Republic of">@changeLang('Iran, Islamic Republic of')</option>
<option value="Iraq">@changeLang('Iraq')</option>
<option value="Ireland">@changeLang('Ireland')</option>
<option value="Isle of Man">@changeLang('Isle of Man')</option>
<option value="Israel">@changeLang('Israel')</option>
<option value="Italy">@changeLang('Italy')</option>
<option value="Jamaica">@changeLang('Jamaica')</option>
<option value="Japan">@changeLang('Japan')</option>
<option value="Jersey">@changeLang('Jersey')</option>
<option value="Jordan">@changeLang('Jordan')</option>
<option value="Kazakhstan">@changeLang('Kazakhstan')</option>
<option value="Kenya">@changeLang('Kenya')</option>
<option value="Kiribati">@changeLang('Kiribati')</option>
<option value="Korea, Democratic People's Republic of">@changeLang('Korea, Democratic People\'s Republic of')</option>
<option value="Korea, Republic of">@changeLang('Korea, Republic of')</option>
<option value="Kuwait">@changeLang('Kuwait')</option>
<option value="Kyrgyzstan">@changeLang('Kyrgyzstan')</option>
<option value="Lao People's Democratic Republic">@changeLang('Lao People\'s Democratic Republic')</option>
<option value="Latvia">@changeLang('Latvia')</option>
<option value="Lebanon">@changeLang('Lebanon')</option>
<option value="Lesotho">@changeLang('Lesotho')</option>
<option value="Liberia">@changeLang('Liberia')</option>
<option value="Libyan Arab Jamahiriya">@changeLang('Libyan Arab Jamahiriya')</option>
<option value="Liechtenstein">@changeLang('Liechtenstein')</option>
<option value="Lithuania">@changeLang('Lithuania')</option>
<option value="Luxembourg">@changeLang('Luxembourg')</option>
<option value="Macao">@changeLang('Macao')</option>
<option value="Macedonia, The Former Yugoslav Republic of">@changeLang('Macedonia, The Former Yugoslav Republic of')</option>
<option value="Madagascar">@changeLang('Madagascar')</option>
<option value="Malawi">@changeLang('Malawi')</option>
<option value="Malaysia">@changeLang('Malaysia')</option>
<option value="Maldives">@changeLang('Maldives')</option>
<option value="Mali">@changeLang('Mali')</option>
<option value="Malta">@changeLang('Malta')</option>
<option value="Marshall Islands">@changeLang('Marshall Islands')</option>
<option value="Martinique">@changeLang('Martinique')</option>
<option value="Mauritania">@changeLang('Mauritania')</option>
<option value="Mauritius">@changeLang('Mauritius')</option>
<option value="Mayotte">@changeLang('Mayotte')</option>
<option value="Mexico">@changeLang('Mexico')</option>
<option value="Micronesia, Federated States of">@changeLang('Micronesia, Federated States of')</option>
<option value="Moldova, Republic of">@changeLang('Moldova, Republic of')</option>
<option value="Monaco">@changeLang('Monaco')</option>
<option value="Mongolia">@changeLang('Mongolia')</option>
<option value="Montenegro">@changeLang('Montenegro')</option>
<option value="Montserrat">@changeLang('Montserrat')</option>
<option value="Morocco">@changeLang('Morocco')</option>
<option value="Mozambique">@changeLang('Mozambique')</option>
<option value="Myanmar">@changeLang('Myanmar')</option>
<option value="Namibia">@changeLang('Namibia')</option>
<option value="Nauru">@changeLang('Nauru')</option>
<option value="Nepal">@changeLang('Nepal')</option>
<option value="Netherlands">@changeLang('Netherlands')</option>
<option value="Netherlands Antilles">@changeLang('Netherlands Antilles')</option>
<option value="New Caledonia">@changeLang('New Caledonia')</option>
<option value="New Zealand">@changeLang('New Zealand')</option>
<option value="Nicaragua">@changeLang('Nicaragua')</option>
<option value="Niger">@changeLang('Niger')</option>
<option value="Nigeria">@changeLang('Nigeria')</option>
<option value="Niue">@changeLang('Niue')</option>
<option value="Norfolk Island">@changeLang('Norfolk Island')</option>
<option value="Northern Mariana Islands">@changeLang('Northern Mariana Islands')</option>
<option value="Norway">@changeLang('Norway')</option>
<option value="Oman">@changeLang('Oman')</option>
<option value="Pakistan">@changeLang('Pakistan')</option>
<option value="Palau">@changeLang('Palau')</option>
<option value="Palestinian Territory, Occupied">@changeLang('Palestinian Territory, Occupied')</option>
<option value="Panama">@changeLang('Panama')</option>
<option value="Papua New Guinea">@changeLang('Papua New Guinea')</option>
<option value="Paraguay">@changeLang('Paraguay')</option>
<option value="Peru">@changeLang('Peru')</option>
<option value="Philippines">@changeLang('Philippines')</option>
<option value="Pitcairn">@changeLang('Pitcairn')</option>
<option value="Poland">@changeLang('Poland')</option>
<option value="Portugal">@changeLang('Portugal')</option>
<option value="Puerto Rico">@changeLang('Puerto Rico')</option>
<option value="Qatar">@changeLang('Qatar')</option>
<option value="Reunion">@changeLang('Reunion')</option>
<option value="Romania">@changeLang('Romania')</option>
<option value="Russian Federation">@changeLang('Russian Federation')</option>
<option value="Rwanda">@changeLang('Rwanda')</option>
<option value="Saint Helena">@changeLang('Saint Helena')</option>
<option value="Saint Kitts and Nevis">@changeLang('Saint Kitts and Nevis')</option>
<option value="Saint Lucia">@changeLang('Saint Lucia')</option>
<option value="Saint Pierre and Miquelon">@changeLang('Saint Pierre and Miquelon')</option>
<option value="Saint Vincent and The Grenadines">@changeLang('Saint Vincent and The Grenadines')</option>
<option value="Samoa">@changeLang('Samoa')</option>
<option value="San Marino">@changeLang('San Marino')</option>
<option value="Sao Tome and Principe">@changeLang('Sao Tome and Principe')</option>
<option value="Saudi Arabia">@changeLang('Saudi Arabia')</option>
<option value="Senegal">@changeLang('Senegal')</option>
<option value="Serbia">@changeLang('Serbia')</option>
<option value="Seychelles">@changeLang('Seychelles')</option>
<option value="Sierra Leone">@changeLang('Sierra Leone')</option>
<option value="Singapore">@changeLang('Singapore')</option>
<option value="Slovakia">@changeLang('Slovakia')</option>
<option value="Slovenia">@changeLang('Slovenia')</option>
<option value="Solomon Islands">@changeLang('Solomon Islands')</option>
<option value="Somalia">@changeLang('Somalia')</option>
<option value="South Africa">@changeLang('South Africa')</option>
<option value="South Georgia and The South Sandwich Islands">@changeLang('South Georgia and The South Sandwich Islands')</option>
<option value="Spain">@changeLang('Spain')</option>
<option value="Sri Lanka">@changeLang('Sri Lanka')</option>
<option value="Sudan">@changeLang('Sudan')</option>
<option value="Suriname">@changeLang('Suriname')</option>
<option value="Svalbard and Jan Mayen">@changeLang('Svalbard and Jan Mayen')</option>
<option value="Swaziland">@changeLang('Swaziland')</option>
<option value="Sweden">@changeLang('Sweden')</option>
<option value="Switzerland">@changeLang('Switzerland')</option>
<option value="Syrian Arab Republic">@changeLang('Syrian Arab Republic')</option>
<option value="Taiwan">@changeLang('Taiwan')</option>
<option value="Tajikistan">@changeLang('Tajikistan')</option>
<option value="Tanzania, United Republic of">@changeLang('Tanzania, United Republic of')</option>
<option value="Thailand">@changeLang('Thailand')</option>
<option value="Timor-leste">@changeLang('Timor-leste')</option>
<option value="Togo">@changeLang('Togo')</option>
<option value="Tokelau">@changeLang('Tokelau')</option>
<option value="Tonga">@changeLang('Tonga')</option>
<option value="Trinidad and Tobago">@changeLang('Trinidad and Tobago')</option>
<option value="Tunisia">@changeLang('Tunisia')</option>
<option value="Turkey">@changeLang('Turkey')</option>
<option value="Turkmenistan">@changeLang('Turkmenistan')</option>
<option value="Turks and Caicos Islands">@changeLang('Turks and Caicos Islands')</option>
<option value="Tuvalu">@changeLang('Tuvalu')</option>
<option value="Uganda">@changeLang('Uganda')</option>
<option value="Ukraine">@changeLang('Ukraine')</option>
<option value="United Arab Emirates">@changeLang('United Arab Emirates')</option>
<option value="United Kingdom">@changeLang('United Kingdom')</option>
<option value="United States">@changeLang('United States')</option>
<option value="United States Minor Outlying Islands">@changeLang('United States Minor Outlying Islands')</option>
<option value="Uruguay">@changeLang('Uruguay')</option>
<option value="Uzbekistan">@changeLang('Uzbekistan')</option>
<option value="Vanuatu">@changeLang('Vanuatu')</option>
<option value="Venezuela">@changeLang('Venezuela')</option>
<option value="Viet Nam">@changeLang('Viet Nam')</option>
<option value="Virgin Islands, British">@changeLang('Virgin Islands, British')</option>
<option value="Virgin Islands, U.S.">@changeLang('Virgin Islands, U.S.')</option>
<option value="Wallis and Futuna">@changeLang('Wallis and Futuna')</option>
<option value="Western Sahara">@changeLang('Western Sahara')</option>
<option value="Yemen">@changeLang('Yemen')</option>
<option value="Zambia">@changeLang('Zambia')</option>
<option value="Zimbabwe">@changeLang('Zimbabwe')</option>
